### ISSUE TITLE
Selecting tablets with appropriate size

### ISSUE THREAD

**Issue by frostme** [RazorX2/magicmirror#1]
finding 2 appropriate sized android tablets

**Comment by aavenoso** [comment]
The nvidia shield k1 has an 8" screen and is only $199

**Comment by vishaltandale00** [comment]
http://www.microcenter.com/product/408819/Webcam_C170_Black

**Comment by prounder** [comment]
https://www.amazon.com/dp/B00MLI3AE2

was the tablet we ordered: 7", snapdragon 400 processor, 1.3 MP front facing camera
