### ISSUE TITLE
Research, Locate and Order Materials

### ISSUE THREAD

**Issue by frostme** [RazorX2/magicmirror#2]
- Picture frame
- two-way mirror

**Comment by prounder** [comment]
https://www.amazon.com/dp/B00MLI3AE2

for tablet

**Comment by frostme** [comment]
@RazorX2/interns  If there is a general consensus on frame and mirror materials please note it here before we mark it as Closed.

**Comment by prounder** [comment]
received 12x12 frame and mirror
