### ISSUE TITLE
Research Facial Recognition

### ISSUE THREAD

**Issue by frostme** [RazorX2/magicmirror#5]
- potential libraries
- implementation guides

**Comment by prounder** [comment]
opencv includes eigenfaces, fisherfaces, and linear binary pattern histograms (LBPH) recognition methods.

eigenfaces: overall image, heavily dependent on specific conditions
fisherfaces: designed to ignore lighting conditions, still not very accurate
LBPH: detects texture? apparently

all three methods require a set of frontal facing shots with slight variations in angle, illumination, and facial expression.

the best method seems to be detecting the face, warping it to be front facing, using a histogram to equalize the light levels, and then try using all three methods?

http://stackoverflow.com/questions/21339307/how-to-get-better-results-with-opencv-face-recognition-module

**Comment by prounder** [comment]
snapdragon has built in facial recognition for its mobile products (phones + tablets) for S4, 200, 400, 600, or 800 processors.

there are no reviews on its capabilities/accuracy, and the cheapest tablets with snapdragon cores start at at least $120.

http://code.tutsplus.com/tutorials/identifying-people-with-qualcomms-snapdragon-sdk--cms-22831

**Comment by prounder** [comment]
android opencv github sources:
https://github.com/ayuso2013/face-recognition
https://github.com/Ajay191191/Opencv-Face-Recognition
https://github.com/lukaspili/Android-Face-Recognition
https://github.com/kairosinc/Kairos-SDK-Android

**Comment by prounder** [comment]
decided snapdragon
